### ISSUE TITLE
Panic reflect: slice index out of range

### ISSUE THREAD

**Issue by voron** [bnb-chain/bsc#1238]
#### System information
Image `ghcr.io/bnb-chain/bsc:1.1.18_hf` is used
Geth version: `geth version`
```
Geth
Version: 1.1.18
Git Commit: cb9e50bdf62c6b46a71724066d39f9851181a5af
Architecture: amd64
Go Version: go1.17.13
Operating System: linux
GOPATH=
GOROOT=go
```
OS & Version: Windows/Linux/OSX
`Linux 5.10.147+`
Commit hash : (if `develop`)

#### Expected behaviour
Geth works as usual

#### Actual behaviour
Geth fails with the panic

#### Steps to reproduce the behaviour
Run BSC node with a lot of p2p peers(500 is our case) for some time

#### Backtrace

````
panic: reflect: slice index out of range

goroutine 1851 [running]:
reflect.Value.Index({0x14abf00, 0xc042658180, 0x14}, 0xc0b2fcc000)
	reflect/value.go:1310 +0x178
github.com/ethereum/go-ethereum/rlp.makeSliceWriter.func2({0x14abf00, 0xc042658180, 0xc0b2fcc000}, 0xc0b2fcc000)
	github.com/ethereum/go-ethereum/rlp/encode.go:307 +0x1b5
github.com/ethereum/go-ethereum/rlp.makeStructWriter.func1({0x16208a0, 0xc042658168, 0x20}, 0xc0b2fcc000)
	github.com/ethereum/go-ethereum/rlp/encode.go:336 +0x17b
github.com/ethereum/go-ethereum/rlp.makeSliceWriter.func2({0x14a57c0, 0xc010620128, 0xc1bbf7f428}, 0xc0b2fcc000)
	github.com/ethereum/go-ethereum/rlp/encode.go:307 +0x1cf
github.com/ethereum/go-ethereum/rlp.makeStructWriter.func1({0x16c05c0, 0xc0106200a0, 0x16c05c0}, 0xc0b2fcc000)
	github.com/ethereum/go-ethereum/rlp/encode.go:336 +0x17b
github.com/ethereum/go-ethereum/rlp.(*encBuffer).encode(0xa0, {0x16c05c0, 0xc0106200a0})
	github.com/ethereum/go-ethereum/rlp/encbuffer.go:175 +0x104
github.com/ethereum/go-ethereum/rlp.Encode({0x1cc5620, 0xc0b2fcc000}, {0x16c05c0, 0xc0106200a0})
	github.com/ethereum/go-ethereum/rlp/encode.go:60 +0x1b8
github.com/ethereum/go-ethereum/core/types.(*DiffLayer).EncodeRLP(0xc18268e000, {0x1cc5620, 0xc0b2fcc000})
	github.com/ethereum/go-ethereum/core/types/block.go:484 +0x1c5
github.com/ethereum/go-ethereum/rlp.makeEncoderWriter.func2({0x16d0de0, 0xc18268e000, 0x1533140}, 0xc106924780)
	github.com/ethereum/go-ethereum/rlp/encode.go:400 +0xb3
github.com/ethereum/go-ethereum/rlp.makePtrWriter.func1({0x1590840, 0xc18268e000, 0x1590840}, 0xc0b2fcc000)
	github.com/ethereum/go-ethereum/rlp/encode.go:379 +0xc2
github.com/ethereum/go-ethereum/rlp.(*encBuffer).encode(0xc18268e000, {0x1590840, 0xc18268e000})
	github.com/ethereum/go-ethereum/rlp/encbuffer.go:175 +0x104
github.com/ethereum/go-ethereum/rlp.EncodeToBytes({0x1590840, 0xc18268e000})
	github.com/ethereum/go-ethereum/rlp/encode.go:77 +0xd8
github.com/ethereum/go-ethereum/core.(*BlockChain).GetDiffLayerRLP(0xc0001f6000, {0xa5, 0x81, 0xf9, 0x76, 0xf9, 0x5f, 0x15, 0x7d, 0xb0, ...})
	github.com/ethereum/go-ethereum/core/blockchain.go:979 +0x23a
github.com/ethereum/go-ethereum/eth/protocols/diff.answerDiffLayersQuery({0x1cf2740, 0xc0002d90e0}, 0x1cc4480)
	github.com/ethereum/go-ethereum/eth/protocols/diff/handler.go:165 +0x145
github.com/ethereum/go-ethereum/eth/protocols/diff.handleMessage({0x1cf2740, 0xc0002d90e0}, 0xc0189b85a0)
	github.com/ethereum/go-ethereum/eth/protocols/diff/handler.go:123 +0xbac
github.com/ethereum/go-ethereum/eth/protocols/diff.Handle({0x1cf2740, 0xc0002d90e0}, 0xc0189b85a0)
	github.com/ethereum/go-ethereum/eth/protocols/diff/handler.go:83 +0x3d
github.com/ethereum/go-ethereum/eth/protocols/diff.MakeProtocols.func2.1(0xc000201f80)
	github.com/ethereum/go-ethereum/eth/protocols/diff/handler.go:63 +0x68
github.com/ethereum/go-ethereum/eth.(*handler).runDiffExtension(0xc0002d90e0, 0xc0189b85a0, 0xc0072ee0a8)
	github.com/ethereum/go-ethereum/eth/handler.go:515 +0x1db
github.com/ethereum/go-ethereum/eth.(*diffHandler).RunPeer(0xc0002d90e0, 0xc0189b85a0, 0x1cd4cd0)
	github.com/ethereum/go-ethereum/eth/handler_diff.go:51 +0x13b
github.com/ethereum/go-ethereum/eth/protocols/diff.MakeProtocols.func2(0x0, {0x1cd4cd0, 0xc008f88000})
	github.com/ethereum/go-ethereum/eth/protocols/diff/handler.go:61 +0xa2
github.com/ethereum/go-ethereum/p2p.(*Peer).startProtocols.func1()
	github.com/ethereum/go-ethereum/p2p/peer.go:433 +0x8c
created by github.com/ethereum/go-ethereum/p2p.(*Peer).startProtocols
	github.com/ethereum/go-ethereum/p2p/peer.go:431 +0xb3

````

When submitting logs: please submit them as text and not screenshots.

**Comment by owen-reorg** [comment]
The cause might be the concurrent writing of the `diffLayer`.

https://github.com/bnb-chain/bsc/blob/cb9e50bdf62c6b46a71724066d39f9851181a5af/core/state_processor.go#L108-L135

Could you try to re-run BSC node without `--diffsync` flag?

**Comment by voron** [comment]
>Could you try to re-run BSC node without --diffsync flag?

Testing, will let you know the results in some time.

**Comment by bnb-tw** [comment]
@voron is this still an issue for you?
