### ISSUE TITLE
Parlia slice bounds out of range

### ISSUE THREAD

**Issue by Davincible** [bnb-chain/bsc#1286]
```
nft-marketplace-bsc-miner-1  | panic: runtime error: slice bounds out of range [:-65]
nft-marketplace-bsc-miner-1  | 
nft-marketplace-bsc-miner-1  | goroutine 102 [running]:
nft-marketplace-bsc-miner-1  | github.com/ethereum/go-ethereum/consensus/parlia.(*Parlia).snapshot(0xc000976f00, {0x1ce6d20, 0xc000977400}, 0x8?, {0xa3, 0xfa, 0x5d, 0xc3, 0x93, 0xe4, ...}, ...)
nft-marketplace-bsc-miner-1  | 	github.com/ethereum/go-ethereum/consensus/parlia/parlia.go:464 +0xd0a
nft-marketplace-bsc-miner-1  | github.com/ethereum/go-ethereum/consensus/parlia.(*Parlia).Prepare(0xc000976f00, {0x1ce6d20, 0xc000977400}, 0xc000968480)
nft-marketplace-bsc-miner-1  | 	github.com/ethereum/go-ethereum/consensus/parlia/parlia.go:602 +0xf8
nft-marketplace-bsc-miner-1  | github.com/ethereum/go-ethereum/miner.(*worker).prepareWork(0xc00064a480, 0xc0022c9b70)
nft-marketplace-bsc-miner-1  | 	github.com/ethereum/go-ethereum/miner/worker.go:974 +0x9a5
nft-marketplace-bsc-miner-1  | github.com/ethereum/go-ethereum/miner.(*worker).commitWork(0xc00064a480, 0xc002039650, 0x63d6e8ab)
nft-marketplace-bsc-miner-1  | 	github.com/ethereum/go-ethereum/miner/worker.go:1101 +0x3a5
nft-marketplace-bsc-miner-1  | github.com/ethereum/go-ethereum/miner.(*worker).mainLoop(0xc00064a480)
nft-marketplace-bsc-miner-1  | 	github.com/ethereum/go-ethereum/miner/worker.go:479 +0x745
nft-marketplace-bsc-miner-1  | created by github.com/ethereum/go-ethereum/miner.newWorker
nft-marketplace-bsc-miner-1  | 	github.com/ethereum/go-ethereum/miner/worker.go:276 +0x7b6
```

**Comment by brilliant-lx** [comment]
investigating.

**Comment by Davincible** [comment]
This happens when you don't send the 'extraData' field btw

**Comment by brilliant-lx** [comment]
> 

we can add a check for the length of extraData.
but why would you empty the `extraData` element, it should not be empty in BSC's block header.

**Comment by Davincible** [comment]
At the time the issue occurred I hadn't purposefully emptied the `extraData`, I was trying to set up a local network, and only added the parlia consensus block, without the rest. 

So arguably user fault, due to lack of documentation. But an error message hinting to what's wrong would be nice.

**Comment by brilliant-lx** [comment]
> 

Yes, we will add an error message for it, it will make it clearer.
BTW, 
"due to lack of documentation": I am not sure, but there may not have published document on how to setup local BSC dev net, right? If there is one, we can improve it.

**Comment by Davincible** [comment]
> I am not sure, but there may not have published document on how to setup local BSC dev net, right?

Yes, no docs available

**Comment by brilliant-lx** [comment]
The error message was added, it will dump error message once extraData is empty in genesis block
