### ISSUE TITLE
error: no suitable peers available

### ISSUE THREAD

**Issue by madhan5447** [bnb-chain/bsc#1487]
I am using a light node v1.1.23, The following error occurs while submitting requests to GetBalance:

Error: getDeleteStateObject (b02a90Oik928lach8f727f7b) error: no suitable peers available
	at web3.js:6365:9(45)
	at send (web3.js:5099:62(34))
	at <eval>:1:20(5)

Geth version : Geth/v1.1.23-48aaee69/linux-amd64/go1.19.8

net.peerCount
142

Please provide a solution for this problem.

**Comment by 0xLyon** [comment]
I there, as discussed on discord, we are checking on this and will advice once we have some additional feedback for this.

**Comment by isaacyuno** [comment]
When did you start to have this issue? Since 1.1.23?

**Comment by madhan5447** [comment]
I began our node on April 17, 2023, while occur this error, multiple time i was restarted our node , however the problem keep going.
