### ISSUE TITLE
crash when statedb.Commit

### ISSUE THREAD

**Issue by NathanBSC** [bnb-chain/bsc#1607]
#### System information

panic: interface conversion: state.Trie is *trie.EmptyTrie, not *trie.SecureTrie

```
goroutine 52254 [running]:
github.com/ethereum/go-ethereum/core/state.(*cachingDB).CacheAccount(0xc038e35440?, {0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...}, ...)
        github.com/ethereum/go-ethereum/core/state/database.go:246 +0x146
github.com/ethereum/go-ethereum/core/state.(*StateDB).Commit.func1.1(0xc038e35440, 0x0?, {0xc04cd480b0, 0x1, 0xc023f66c00?})
        github.com/ethereum/go-ethereum/core/state/statedb.go:1494 +0xa29
github.com/ethereum/go-ethereum/core/state.(*StateDB).Commit.func1()
        github.com/ethereum/go-ethereum/core/state/statedb.go:1506 +0x56
github.com/ethereum/go-ethereum/core/state.(*StateDB).Commit.func4()
        github.com/ethereum/go-ethereum/core/state/statedb.go:1599 +0x29
created by github.com/ethereum/go-ethereum/core/state.(*StateDB).Commit
        github.com/ethereum/go-ethereum/core/state/statedb.go:1598 +0x754
```

check code
<img width="817" alt="image" src="https://github.com/bnb-chain/bsc/assets/122502194/845e81b4-8c78-4d82-82ce-0871bf4cc589">

when trie is a EmptyTrie, root is `common.Hash{}`
but `emptyRoot` is  
<img width="762" alt="image" src="https://github.com/bnb-chain/bsc/assets/122502194/2166c7ca-3820-4e26-ab69-9ff7aa6d66bb">
so not hold back by `if root != emptyRoot `, crash then
<img width="448" alt="image" src="https://github.com/bnb-chain/bsc/assets/122502194/d43242e7-3627-4759-b581-97eb31a0fc63">

#### Backtrace

````
[backtrace]
````

When submitting logs: please submit them as text and not screenshots.

**Comment by NathanBSC** [comment]
![image](https://github.com/bnb-chain/bsc/assets/122502194/3ffcbf3f-67fb-4d40-a66b-22b1b03b7ed6)
