### ISSUE TITLE
Node crashing

### ISSUE THREAD

**Issue by ItalianAlpha** [bnb-chain/bsc#1807]
#### System information

Geth version: 1.2.19/1.2.20
OS & Version: Linux
Server specifications:
Hosting provider: Hetzner
RAM: 64GB
SSD: 4TB NVME
CPU: 32T
#### Expected behaviour

Sync node from the snapshot without any issue.

#### Actual behaviour

Node crashes after starting sync process, I get connect at max to 2 peers, added peers from https://api.binance.org/v1/discovery/peers
I've tried to change Go version, Bsc-Geth version, download Snapshot again, but I'm still getting this issue.

#### Steps to reproduce the behaviour

Sync the node from the snapshot.

#### Backtrace

Bsc.log
````
t=2023-08-07T10:04:40+0200 lvl=info msg="Imported new chain segment"            blocks=175  txs=15717 mgas=1608.363 elapsed=8.025s      mgasps=200.406 number=30,140,559 hash=0xcf257589e050059b735c8ffcf70de7bf0532581105aa143a350f9d142b144914 age=2w3d9h   dirty="757.61 MiB"
t=2023-08-07T10:04:48+0200 lvl=info msg="Imported new chain segment"            blocks=175  txs=15524 mgas=1563.193 elapsed=8.007s      mgasps=195.205 number=30,140,734 hash=0x3f9f793f6953cda9bbb05b63c240875059b4dec3cd69a0d3b6db1010d35f7087 age=2w3d8h   dirty="785.08 MiB"
t=2023-08-07T10:04:57+0200 lvl=info msg="Imported new chain segment"            blocks=95   txs=8334  mgas=1009.237 elapsed=8.224s      mgasps=122.705 number=30,140,829 hash=0x0dad4b290aeb7a6802447d2359a6c410b40fd8ac54c15b8a33af6d2143c6493e age=2w3d8h   dirty="822.48 MiB"
t=2023-08-07T10:04:57+0200 lvl=info msg="Looking for peers"  
````
Crash log
````
INFO [08-07|09:47:55.904] Starting Geth on Ethereum mainnet... 
INFO [08-07|09:47:55.905] Maximum peer count                       ETH=200 LES=0 total=200
unexpected fault address 0x0
fatal error: fault
[signal SIGSEGV: segmentation violation code=0x80 addr=0x0 pc=0xf93500]

goroutine 2547 [running]:
runtime.throw({0x249fb37?, 0x57988be52af554c1?})
	/opt/hostedtoolcache/go/1.19.11/x64/src/runtime/panic.go:1047 +0x5d fp=0xc2421a5d40 sp=0xc2421a5d10 pc=0x43b6fd
runtime.sigpanic()
	/opt/hostedtoolcache/go/1.19.11/x64/src/runtime/signal_unix.go:846 +0x2c5 fp=0xc2421a5d90 sp=0xc2421a5d40 pc=0x452485
github.com/ethereum/go-ethereum/core/vm.makePush.func1(0xc16a1c5f90, 0xc093740a00, 0xc13f7154e8)
	/home/runner/work/bsc/bsc/core/vm/instructions.go:895 fp=0xc2421a5d98 sp=0xc2421a5d90 pc=0xf93500
github.com/ethereum/go-ethereum/core/vm.(*EVMInterpreter).Run(0xc093740a00, 0xc105c4f380, {0xc1ba0bf800, 0x44, 0xc0}, 0x0)
	/home/runner/work/bsc/bsc/core/vm/interpreter.go:249 +0x92d fp=0xc2421a6048 sp=0xc2421a5d98 pc=0xf9452d
github.com/ethereum/go-ethereum/core/vm.(*EVM).Call(0xc111c9eea0, {0x2da06c0, 0xc105c4f2c0}, {0x2a, 0xb0, 0xe9, 0xe4, 0xee, 0x70, 0xff, ...}, ...)
	/home/runner/work/bsc/bsc/core/vm/evm.go:251 +0xb3b fp=0xc2421a6230 sp=0xc2421a6048 pc=0xf82fbb
github.com/ethereum/go-ethereum/core/vm.opCall(0xc111c9eea0?, 0xc093740a00, 0xc13f7154d0)
	/home/runner/work/bsc/bsc/core/vm/instructions.go:698 +0x633 fp=0xc2421a6530 sp=0xc2421a6230 pc=0xf90393
github.com/ethereum/go-ethereum/core/vm.(*EVMInterpreter).Run(0xc093740a00, 0xc105c4f2c0, {0xc20b027c00, 0xe4, 0x100}, 0x0)
	/home/runner/work/bsc/bsc/core/vm/interpreter.go:249 +0x92d fp=0xc2421a67e0 sp=0xc2421a6530 pc=0xf9452d
github.com/ethereum/go-ethereum/core/vm.(*EVM).DelegateCall(0xc111c9eea0, {0x2da06c0?, 0xc105c4f200}, {0xc0, 0xac, 0x12, 0x5e, 0x44, 0x42, 0x92, ...}, ...)
	/home/runner/work/bsc/bsc/core/vm/evm.go:348 +0x56f fp=0xc2421a6960 sp=0xc2421a67e0 pc=0xf842af
github.com/ethereum/go-ethereum/core/vm.opDelegateCall(0xc111c9eea0?, 0xc093740a00, 0xc13f7154b8)
	/home/runner/work/bsc/bsc/core/vm/instructions.go:764 +0x48a fp=0xc2421a6be0 sp=0xc2421a6960 pc=0xf916ca
github.com/ethereum/go-ethereum/core/vm.(*EVMInterpreter).Run(0xc093740a00, 0xc105c4f200, {0xc10b4ae940, 0xe4, 0x6c0}, 0x0)
	/home/runner/work/bsc/bsc/core/vm/interpreter.go:249 +0x92d fp=0xc2421a6e90 sp=0xc2421a6be0 pc=0xf9452d
github.com/ethereum/go-ethereum/core/vm.(*EVM).Call(0xc111c9eea0, {0x2da06c0, 0xc104a7e840}, {0xb0, 0x4c, 0x5b, 0x9b, 0xb5, 0x1b, 0x82, ...}, ...)
	/home/runner/work/bsc/bsc/core/vm/evm.go:251 +0xb3b fp=0xc2421a7078 sp=0xc2421a6e90 pc=0xf82fbb
github.com/ethereum/go-ethereum/core/vm.opCall(0xc111c9eea0?, 0xc093740a00, 0xc0ffe96d08)
	/home/runner/work/bsc/bsc/core/vm/instructions.go:698 +0x633 fp=0xc2421a7378 sp=0xc2421a7078 pc=0xf90393
github.com/ethereum/go-ethereum/core/vm.(*EVMInterpreter).Run(0xc093740a00, 0xc104a7e840, {0xc1051ea040, 0x1004, 0x1fc0}, 0x0)
	/home/runner/work/bsc/bsc/core/vm/interpreter.go:249 +0x92d fp=0xc2421a7628 sp=0xc2421a7378 pc=0xf9452d
github.com/ethereum/go-ethereum/core/vm.(*EVM).Call(0xc111c9eea0, {0x2da06c0, 0xc104a7e780}, {0x0, 0x71, 0x82, 0x4c, 0xbe, 0xd7, 0xe9, ...}, ...)
	/home/runner/work/bsc/bsc/core/vm/evm.go:251 +0xb3b fp=0xc2421a7810 sp=0xc2421a7628 pc=0xf82fbb
github.com/ethereum/go-ethereum/core/vm.opCall(0xc111c9eea0?, 0xc093740a00, 0xc0ffe96cf0)
	/home/runner/work/bsc/bsc/core/vm/instructions.go:698 +0x633 fp=0xc2421a7b10 sp=0xc2421a7810 pc=0xf90393
github.com/ethereum/go-ethereum/core/vm.(*EVMInterpreter).Run(0xc093740a00, 0xc104a7e780, {0xc0a9ab9400, 0x2064, 0x2064}, 0x0)
	/home/runner/work/bsc/bsc/core/vm/interpreter.go:249 +0x92d fp=0xc2421a7dc0 sp=0xc2421a7b10 pc=0xf9452d
github.com/ethereum/go-ethereum/core/vm.(*EVM).Call(0xc111c9eea0, {0x2daa6e0, 0xc0b1960ae0}, {0x40, 0x27, 0x1e, 0x1a, 0xbe, 0xee, 0x36, ...}, ...)
	/home/runner/work/bsc/bsc/core/vm/evm.go:251 +0xb3b fp=0xc2421a7fa8 sp=0xc2421a7dc0 pc=0xf82fbb
github.com/ethereum/go-ethereum/core.(*StateTransition).TransitionDb(0xc125a9ad80)
	/home/runner/work/bsc/bsc/core/state_transition.go:345 +0x925 fp=0xc2421a82a0 sp=0xc2421a7fa8 pc=0xff38c5
github.com/ethereum/go-ethereum/core.ApplyMessage(0x240b580?, {0x2dd25e0?, 0xc14bdadcb0?}, 0xc08115bd20?)
	/home/runner/work/bsc/bsc/core/state_transition.go:184 +0x2a fp=0xc2421a82d0 sp=0xc2421a82a0 pc=0xff1cca
github.com/ethereum/go-ethereum/core.applyTransaction({0xc0b1960a20, {0x86, 0xdb, 0x9e, 0x16, 0x57, 0x98, 0x8b, 0xe5, 0x2a, ...}, ...}, ...)
	/home/runner/work/bsc/bsc/core/state_processor.go:460 +0x1c6 fp=0xc2421a8558 sp=0xc2421a82d0 pc=0xff0d86
github.com/ethereum/go-ethereum/core.(*StateProcessor).Process(0xc002038260, 0xc17f518c00, 0xc0ee301d40, {0x0, {0x0, 0x0}, 0x0, 0x0, 0x0, 0x0, ...})
	/home/runner/work/bsc/bsc/core/state_processor.go:432 +0xcd9 fp=0xc2421a8a98 sp=0xc2421a8558 pc=0xff0459
github.com/ethereum/go-ethereum/core.(*BlockChain).insertChain(0xc0001f7080, {0xc15b4e4000?, 0x800, 0x800}, 0x1, 0x1)
	/home/runner/work/bsc/bsc/core/blockchain.go:1968 +0x1d9a fp=0xc2421a98c8 sp=0xc2421a8a98 pc=0xfc5eba
github.com/ethereum/go-ethereum/core.(*BlockChain).InsertChain(0xc0001f7080, {0xc15b4e4000?, 0x800, 0x800})
	/home/runner/work/bsc/bsc/core/blockchain.go:1744 +0xb51 fp=0xc2421a9c70 sp=0xc2421a98c8 pc=0xfc3f31
github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).importBlockResults(0xc001d71b80, {0xc157302000, 0x800, 0x0?})
	/home/runner/work/bsc/bsc/eth/downloader/downloader.go:1463 +0x47d fp=0xc2421a9f10 sp=0xc2421a9c70 pc=0x1152bdd
github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).processFullSyncContent(0xc001d71b80)
	/home/runner/work/bsc/bsc/eth/downloader/downloader.go:1432 +0xaf fp=0xc2421a9f70 sp=0xc2421a9f10 pc=0x11526ef
github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).processFullSyncContent-fm()
	<autogenerated>:1 +0x26 fp=0xc2421a9f88 sp=0xc2421a9f70 pc=0x11660c6
github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).spawnSync.func1()
	/home/runner/work/bsc/bsc/eth/downloader/downloader.go:628 +0x70 fp=0xc2421a9fe0 sp=0xc2421a9f88 pc=0x114bdb0
runtime.goexit()
	/opt/hostedtoolcache/go/1.19.11/x64/src/runtime/asm_amd64.s:1594 +0x1 fp=0xc2421a9fe8 sp=0xc2421a9fe0 pc=0x470321
created by github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).spawnSync
	/home/runner/work/bsc/bsc/eth/downloader/downloader.go:628 +0x5f

````

**Comment by 0xLyon** [comment]
Hi there, thanks for sharing the details. We will look into this and provide update once available.

**Comment by ItalianAlpha** [comment]
Sure, there you are

`./geth --config ./config.toml --datadir ./node  --cache 8000 --rpc.allow-unprotected-txs --txlookuplimit 0 --tries-verify-mode none`

**Comment by weiihann** [comment]
Hey there! I'll try to reproduce this issue and find out what exactly went wrong. May I get the following information as well: 

1. The different Go versions that you've tried
2. `config.toml` file content

**Comment by ItalianAlpha** [comment]
Hey, I've concluded that the issue was with a faulty CPU. I noticed a few MCE errors, but after changing the CPU, everything went smoothly. Thanks for the swift support!

**Comment by weiihann** [comment]
Thanks for letting us know! :)
