### ISSUE TITLE
runtime error: makeslice: len out of range

### ISSUE THREAD

**Issue by ko0f** [bnb-chain/bsc#1936]
#### System information

Geth version: v1.2.12
OS & Version: Ubuntu 22.04.3 LTS

#### Expected behaviour
It starts normally.

#### Actual behaviour
It crashes right on startup.

#### Steps to reproduce the behaviour

1. Checkout v1.2.12
2. Modify Dockerfile ENTRYPOINT ["geth"] 
3. `docker build -t bsc:latest .`
4. Load Geth full node snapshot: https://github.com/48Club/bsc-snapshots#geth-full-node
5. docker run -it --network bsc -p 8555:8555 -p 8556:8556 -v /bsc:/data bsc:latest console --config /data/config.toml --datadir /data --ws --ws.origins="*" --http --http.corsdomain="*" --txlookuplimit=0 --syncmode=full --tries-verify-mode=none --diffblock=5000 --diffsync --nat=none --cache=10000

#### Backtrace

````
INFO [10-20|12:40:02.050] Starting Geth on Ethereum mainnet... 
INFO [10-20|12:40:02.051] Maximum peer count                       ETH=30 LES=0 total=30
INFO [10-20|12:40:02.051] Smartcard socket not found, disabling    err="stat /run/pcscd/pcscd.comm: no such file or directory"
WARN [10-20|12:40:02.051] Option nousb is deprecated and USB is deactivated by default. Use --usb to enable 
WARN [10-20|12:40:02.051] The --diffsync flag is deprecated and will be removed in the future! 
INFO [10-20|12:40:02.054] Set global gas cap                       cap=50,000,000
INFO [10-20|12:40:02.054] Allocated trie memory caches             clean=1.46GiB dirty=2.44GiB
INFO [10-20|12:40:02.054] Allocated cache and file handles         database=/data/geth/chaindata cache=3.91GiB handles=524,288
panic: runtime error: makeslice: len out of range

goroutine 1 [running]:
github.com/syndtr/goleveldb/leveldb.(*sessionRecord).readBytes(0xc0015ab980, {0x24e086f, 0xd}, {0x7f60a3c3e0a8?, 0xc00011ca80})
	github.com/syndtr/goleveldb@v1.0.1/leveldb/session_record.go:236 +0xb2
github.com/syndtr/goleveldb/leveldb.(*sessionRecord).decode(0xc0015ab980, {0x2db0240?, 0xc00011ca80})
	github.com/syndtr/goleveldb@v1.0.1/leveldb/session_record.go:300 +0x4b7
github.com/syndtr/goleveldb/leveldb.(*session).recover(0xc0001f02d0)
	github.com/syndtr/goleveldb@v1.0.1/leveldb/session.go:170 +0x4d1
github.com/syndtr/goleveldb/leveldb.Open({0x2ddaaa8?, 0xc000660070?}, 0x0?)
	github.com/syndtr/goleveldb@v1.0.1/leveldb/db.go:189 +0xa5
github.com/syndtr/goleveldb/leveldb.OpenFile({0xc0000585d0?, 0x264a5d9?}, 0xc000644000)
	github.com/syndtr/goleveldb@v1.0.1/leveldb/db.go:225 +0x5d
github.com/ethereum/go-ethereum/ethdb/leveldb.NewCustom({0xc0000585d0, 0x14}, {0x256f706, 0x11}, 0x0?)
	github.com/ethereum/go-ethereum/ethdb/leveldb/leveldb.go:120 +0x312
github.com/ethereum/go-ethereum/ethdb/leveldb.New({0xc0000585d0?, 0x1c?}, 0xfa0, 0x80000, {0x256f706?, 0xc0023bdc68?}, 0xea?)
	github.com/ethereum/go-ethereum/ethdb/leveldb/leveldb.go:88 +0x71
github.com/ethereum/go-ethereum/core/rawdb.NewLevelDBDatabaseWithFreezer({0xc0000585d0?, 0x9?}, 0x3167e77?, 0xe0?, {0xc0004362a0, 0x1c}, {0x256f706, 0x11}, 0xd0?, 0x0, ...)
	github.com/ethereum/go-ethereum/core/rawdb/database.go:343 +0x50
github.com/ethereum/go-ethereum/node.(*Node).OpenDatabaseWithFreezer(0xc002178680, {0x24ce105?, 0x7f609a91d848?}, 0xc000450040?, 0x46251e0?, {0x0, 0x0}, {0x256f706, 0x11}, 0x0, ...)
	github.com/ethereum/go-ethereum/node/node.go:658 +0x345
github.com/ethereum/go-ethereum/node.(*Node).OpenAndMergeDatabase(0x3?, {0x24ce105, 0x9}, 0x4?, 0x80000, {0x0?, 0x0?}, {0x0, 0x0}, {0x256f706, ...}, ...)
	github.com/ethereum/go-ethereum/node/node.go:619 +0xe5
github.com/ethereum/go-ethereum/eth.New(0xc002178680, 0xc002116800)
	github.com/ethereum/go-ethereum/eth/backend.go:148 +0x575
github.com/ethereum/go-ethereum/cmd/utils.RegisterEthService(0x0?, 0xc002116800)
	github.com/ethereum/go-ethereum/cmd/utils/flags.go:1915 +0x1e5
main.makeFullNode(0xc0020b3ed0?)
	github.com/ethereum/go-ethereum/cmd/geth/config.go:167 +0x37f
main.localConsole(0x24d13bb?)
	github.com/ethereum/go-ethereum/cmd/geth/consolecmd.go:77 +0x5a
github.com/ethereum/go-ethereum/cmd/utils.MigrateFlags.func1(0xc0020cc2c0)
	github.com/ethereum/go-ethereum/cmd/utils/flags.go:2208 +0x48
gopkg.in/urfave/cli%2ev1.HandleAction({0x20297e0?, 0xc0020b76e0?}, 0x7?)
	gopkg.in/urfave/cli.v1@v1.20.0/app.go:490 +0x5a
gopkg.in/urfave/cli%2ev1.Command.Run({{0x24c82ef, 0x7}, {0x0, 0x0}, {0x0, 0x0, 0x0}, {0x266cd5e, 0x2b}, {0x0, ...}, ...}, ...)
	gopkg.in/urfave/cli.v1@v1.20.0/command.go:210 +0x8f7
gopkg.in/urfave/cli%2ev1.(*App).Run(0xc001fcaea0, {0xc000052120, 0x11, 0x12})
	gopkg.in/urfave/cli.v1@v1.20.0/app.go:255 +0x7e7
main.main()
	github.com/ethereum/go-ethereum/cmd/geth/main.go:282 +0x35
````

When submitting logs: please submit them as text and not screenshots.

**Comment by ko0f** [comment]
I may have been running v1.2.12 with v1.3.0 chaindata.
