### ISSUE TITLE
Uncaught Error Error: transaction indexing is in progress

### ISSUE THREAD

**Issue by tianji6666** [bnb-chain/bsc#2332]
#### System information

Geth version: `1.4.3
OS & Version: Windows

#### Expected behaviour
listen to the mempool

#### Actual behaviour
Uncaught Error Error: transaction indexing is in progress

log in js :

Uncaught Error Error: transaction indexing is in progress
    at WebSocketProvider._this.websocket.onmessage (c:\Users\1\Desktop\jiazi\node_modules\@ethersproject\providers\lib\websocket-provider.js:133:33)
    at callListener (c:\Users\1\node_modules\ws\lib\event-target.js:290:14)
    at onMessage (c:\Users\1\node_modules\ws\lib\event-target.js:209:9)
    at emit (events:514:28)
    at receiverOnMessage (c:\Users\1\node_modules\ws\lib\websocket.js:1209:20)
    at emit (events:514:28)
    at <anonymous> (c:\Users\1\node_modules\ws\lib\receiver.js:608:16)
    at <anonymous> (internal/process/task_queues:140:7)
    at runInAsyncScope (async_hooks:206:9)
    at runMicrotask (internal/process/task_queues:137:8)
    at processTicksAndRejections (internal/process/task_queues:95:5)
websocket-provider.js:133
Process exited with code 1

**Comment by tianji6666** [comment]
![image](https://github.com/bnb-chain/bsc/assets/105796515/ab9b12ba-867c-4532-923e-9e47c0cee048)

**Comment by tianji6666** [comment]
> eth.syncing
{
  currentBlock: 37223484,
  healedBytecodeBytes: 0,
  healedBytecodes: 0,
  healedTrienodeBytes: 0,
  healedTrienodes: 0,
  healingBytecode: 0,
  healingTrienodes: 0,
  highestBlock: 37223481,
  startingBlock: 37223479,
  syncedAccountBytes: 0,
  syncedAccounts: 0,
  syncedBytecodeBytes: 0,
  syncedBytecodes: 0,
  syncedStorage: 0,
  syncedStorageBytes: 0,
  txIndexFinishedBlocks: "0x374100",
  txIndexRemainingBlocks: "0x200bb3d"
}

**Comment by tianji6666** [comment]
there seems like a bug: currentBlock exceeds the highestBlock

**Comment by zzzckck** [comment]
Could provide more detail on how to reproduce the issue?
