### ISSUE TITLE
unexpected fault address 0x0

### ISSUE THREAD

**Issue by perwpqwe** [bnb-chain/bsc#2393]
Geth version:
Version: 1.4.3
Git Commit: https://github.com/bnb-chain/bsc/commit/7f3f72ed410ab4a2ec08951f40037ecc035420d0
Git Commit Date: 20240321
Architecture: amd64
Go Version: go1.21.6
Operating System: linux

start command:
geth --cache 32000 --config /root/config.toml --history.transactions=0 --syncmode=full --db.engine=pebble --state.scheme=path

fatal error: fault
[signal SIGSEGV: segmentation violation code=0x80 addr=0x0 pc=0xa193b6]

goroutine 75470865 [running]:
runtime.throw({0x27124b3?, 0x20?})
	runtime/panic.go:1077 +0x5c fp=0xc0ec64d9a0 sp=0xc0ec64d970 pc=0x43fcbc
runtime.sigpanic()
	runtime/signal_unix.go:875 +0x285 fp=0xc0ec64da00 sp=0xc0ec64d9a0 pc=0x456e05
github.com/ethereum/go-ethereum/core/types.(*Transaction).GasFeeCap(0xc453c96720)
	github.com/ethereum/go-ethereum/core/types/transaction.go:298 +0x36 fp=0xc0ec64da68 sp=0xc0ec64da00 pc=0xa193b6
github.com/ethereum/go-ethereum/core/types.(*Transaction).EffectiveGasTip(0xc880c76c60?, 0xc3e4320520)
	github.com/ethereum/go-ethereum/core/types/transaction.go:367 +0x2a fp=0xc0ec64dac0 sp=0xc0ec64da68 pc=0xa19c4a
github.com/ethereum/go-ethereum/core/types.(*Transaction).EffectiveGasTipValue(...)
	github.com/ethereum/go-ethereum/core/types/transaction.go:377
github.com/ethereum/go-ethereum/core/types.(*Transaction).EffectiveGasTipCmp(0x1?, 0xc6d1db0360?, 0xc3e4320520)
	github.com/ethereum/go-ethereum/core/types/transaction.go:386 +0x39 fp=0xc0ec64daf0 sp=0xc0ec64dac0 pc=0xa19d79
github.com/ethereum/go-ethereum/core/txpool/legacypool.(*priceHeap).cmp(0xc0a64af330?, 0xc89b163620?, 0xc5d7af7320?)
	github.com/ethereum/go-ethereum/core/txpool/legacypool/list.go:525 +0x33 fp=0xc0ec64db28 sp=0xc0ec64daf0 pc=0x13a0433
github.com/ethereum/go-ethereum/core/txpool/legacypool.(*priceHeap).Less(0xc0a64af330, 0x9734ba, 0x9734b9)
	github.com/ethereum/go-ethereum/core/txpool/legacypool/list.go:512 +0x4e fp=0xc0ec64db58 sp=0xc0ec64db28 pc=0x13a030e
container/heap.down({0x3376440, 0xc0a64af330}, 0x0, 0xe0c1a7)
	container/heap/heap.go:108 +0xb0 fp=0xc0ec64dba0 sp=0xc0ec64db58 pc=0x6cef30
container/heap.Pop({0x3376440, 0xc0a64af330})
	container/heap/heap.go:62 +0x59 fp=0xc0ec64dbd8 sp=0xc0ec64dba0 pc=0x6cec19
github.com/ethereum/go-ethereum/core/txpool/legacypool.(*pricedList).Reheap(0xc0a64af320)
	github.com/ethereum/go-ethereum/core/txpool/legacypool/list.go:702 +0x1e5 fp=0xc0ec64dc68 sp=0xc0ec64dbd8 pc=0x13a0f05
github.com/ethereum/go-ethereum/core/txpool/legacypool.(*pricedList).SetBaseFee(...)
	github.com/ethereum/go-ethereum/core/txpool/legacypool/list.go:712
github.com/ethereum/go-ethereum/core/txpool/legacypool.(*LegacyPool).runReorg(0xc0a64f6000, 0xc2f1ebdc20, 0xc7f39e9220, 0x0, 0xc89260be90)
	github.com/ethereum/go-ethereum/core/txpool/legacypool/legacypool.go:1380 +0x667 fp=0xc0ec64dfa8 sp=0xc0ec64dc68 pc=0x1397b67
github.com/ethereum/go-ethereum/core/txpool/legacypool.(*LegacyPool).scheduleReorgLoop.func2()
	github.com/ethereum/go-ethereum/core/txpool/legacypool/legacypool.go:1283 +0x30 fp=0xc0ec64dfe0 sp=0xc0ec64dfa8 pc=0x1397470
runtime.goexit()
	runtime/asm_amd64.s:1650 +0x1 fp=0xc0ec64dfe8 sp=0xc0ec64dfe0 pc=0x476541
created by github.com/ethereum/go-ethereum/core/txpool/legacypool.(*LegacyPool).scheduleReorgLoop in goroutine 4618
	github.com/ethereum/go-ethereum/core/txpool/legacypool/legacypool.go:1283 +0x192

**Comment by emailtovamos** [comment]
Could you share the config.toml ?

**Comment by perwpqwe** [comment]
> Could you share the config.toml ?

[Eth]
NetworkId = 56
LightServ = 0
SyncMode = "full"
TransactionHistory = 0
# PruneAncientData = true
TriesVerifyMode = "none"

[Eth.TxPool]
PriceLimit = 1000000000

[Node]
HTTPHost = "localhost"
HTTPPort = 8545
# DBEngine = "pebble"

[Node.P2P]
MaxPeers = 10000
MaxPeersPerIP = 3
ListenAddr = ":30311"

[Node.LogConfig]
Level = "info"
FileRoot = ""
FilePath = "bsc.log"
RotateHours = 0
MaxBytesSize = 104857600

**Comment by emailtovamos** [comment]
Ok thanks. Could you provide your bsc.log file?

**Comment by emailtovamos** [comment]
Closing for now, happy to reopen once given more info as asked above.
