### ISSUE TITLE
UT "TestSnapSyncWithBlobs" random fail

### ISSUE THREAD

**Issue by zzzckck** [bnb-chain/bsc#2489]
#### System information

Geth version: `v1.4.8`
OS & Version: Windows/Linux/OSX
Commit hash : (if `develop`)

#### Expected behaviour
UT should not failed

#### Actual behaviour
it failed

#### Steps to reproduce the behaviour
Random fail, check the failed log: https://github.com/bnb-chain/bsc/actions/runs/9184422166/job/25256710320?pr=2487

#### Backtrace

````

panic: test timed out after 1h0m0s
running tests:
	TestSnapSyncWithBlobs (1h0m0s)

goroutine 70838 [running]:
testing.(*M).startAlarm.func1()
	/opt/hostedtoolcache/go/1.21.11/x64/src/testing/testing.go:2259 +0x3b9
created by time.goFunc
	/opt/hostedtoolcache/go/1.21.11/x64/src/time/sleep.go:176 +0x2d

goroutine 1 [chan receive, 59 minutes]:
testing.tRunner.func1()
	/opt/hostedtoolcache/go/1.21.11/x64/src/testing/testing.go:1561 +0x489
testing.tRunner(0xc00158c1a0, 0xc001f97c48)
	/opt/hostedtoolcache/go/1.21.11/x64/src/testing/testing.go:1601 +0x138
testing.runTests(0xc00014c1e0?, {0x2d72bc0, 0x1b, 0x1b}, {0xc?, 0xc001f97d08?, 0x2e131c0?})
	/opt/hostedtoolcache/go/1.21.11/x64/src/testing/testing.go:2052 +0x445
testing.(*M).Run(0xc00014c1e0)
	/opt/hostedtoolcache/go/1.21.11/x64/src/testing/testing.go:1925 +0x636
main.main()
	_testmain.go:99 +0x19c

goroutine 6 [chan receive]:
github.com/panjf2000/ants/v2.(*Pool).purgePeriodically(0xc0000d21c0)
	/home/runner/go/pkg/mod/github.com/panjf2000/ants/v2@v2.4.5/pool.go:69 +0x85
created by github.com/panjf2000/ants/v2.NewPool in goroutine 1
	/home/runner/go/pkg/mod/github.com/panjf2000/ants/v2@v2.4.5/pool.go:137 +0x325

goroutine 7 [chan receive]:
github.com/panjf2000/ants/v2.(*Pool).purgePeriodically(0xc0000d2230)
	/home/runner/go/pkg/mod/github.com/panjf2000/ants/v2@v2.4.5/pool.go:69 +0x85
created by github.com/panjf2000/ants/v2.NewPool in goroutine 1
	/home/runner/go/pkg/mod/github.com/panjf2000/ants/v2@v2.4.5/pool.go:137 +0x325

goroutine 10 [select, 60 minutes]:
github.com/dgraph-io/ristretto.(*defaultPolicy).processItems(0xc0001ce080)
	/home/runner/go/pkg/mod/github.com/dgraph-io/ristretto@v0.0.4-0.20210318174700-74754f61e018/policy.go:102 +0x85
created by github.com/dgraph-io/ristretto.newDefaultPolicy in goroutine 1
	/home/runner/go/pkg/mod/github.com/dgraph-io/ristretto@v0.0.4-0.20210318174700-74754f61e018/policy.go:86 +0x139

goroutine 11 [select]:
github.com/dgraph-io/ristretto.(*Cache).processItems(0xc0002ae000)
	/home/runner/go/pkg/mod/github.com/dgraph-io/ristretto@v0.0.4-0.20210318174700-74754f61e018/cache.go:422 +0x149
created by github.com/dgraph-io/ristretto.NewCache in goroutine 1
	/home/runner/go/pkg/mod/github.com/dgraph-io/ristretto@v0.0.4-0.20210318174700-74754f61e018/cache.go:204 +0x645

goroutine 29177 [select, 59 minutes]:
github.com/ethereum/go-ethereum/eth.(*handler).protoTracker(0xc001a86160)
	/home/runner/work/bsc/bsc/eth/handler.go:380 +0xe6
created by github.com/ethereum/go-ethereum/eth.(*handler).Start in goroutine 4351
	/home/runner/work/bsc/bsc/eth/handler.go:741 +0x465

goroutine 29202 [select, 59 minutes]:
github.com/ethereum/go-ethereum/eth/fetcher.(*BlockFetcher).loop(0xc005dff4a0)
	/home/runner/work/bsc/bsc/eth/fetcher/block_fetcher.go:399 +0x365
created by github.com/ethereum/go-ethereum/eth/fetcher.(*BlockFetcher).Start in goroutine 29176
	/home/runner/work/bsc/bsc/eth/fetcher/block_fetcher.go:250 +0x4f

goroutine 29185 [select, 59 minutes]:
github.com/ethereum/go-ethereum/eth/protocols/eth.(*Peer).dispatcher(0xc005dff680)
	/home/runner/work/bsc/bsc/eth/protocols/eth/dispatcher.go:192 +0x152
created by github.com/ethereum/go-ethereum/eth/protocols/eth.NewPeer in goroutine 4351
	/home/runner/work/bsc/bsc/eth/protocols/eth/peer.go:123 +0x5c5

goroutine 29065 [select, 59 minutes]:
github.com/ethereum/go-ethereum/eth.(*handler).protoTracker(0xc007b5adc0)
	/home/runner/work/bsc/bsc/eth/handler.go:380 +0xe6
created by github.com/ethereum/go-ethereum/eth.(*handler).Start in goroutine 4351
	/home/runner/work/bsc/bsc/eth/handler.go:741 +0x465

goroutine 29087 [select, 59 minutes]:
github.com/ethereum/go-ethereum/eth/fetcher.(*BlockFetcher).loop(0xc005dff0e0)
	/home/runner/work/bsc/bsc/eth/fetcher/block_fetcher.go:399 +0x365
created by github.com/ethereum/go-ethereum/eth/fetcher.(*BlockFetcher).Start in goroutine 29064
	/home/runner/work/bsc/bsc/eth/fetcher/block_fetcher.go:250 +0x4f

goroutine 29175 [select, 59 minutes]:
github.com/ethereum/go-ethereum/eth.(*handler).minedBroadcastLoop(0xc001a86160)
	/home/runner/work/bsc/bsc/eth/handler.go:944 +0xc6
created by github.com/ethereum/go-ethereum/eth.(*handler).Start in goroutine 4351
	/home/runner/work/bsc/bsc/eth/handler.go:733 +0x3bb

goroutine 4351 [chan receive, 59 minutes]:
github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).spawnSync(0xc001766d00, {0xc017585080, 0x5, 0xa?})
	/home/runner/work/bsc/bsc/eth/downloader/downloader.go:623 +0x154
github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).syncWithPeer(0xc001766d00, 0xc005e0b800, {0x94, 0xc5, 0x90, 0x52, 0xbb, 0x6e, 0x7d, 0xfe, ...}, ...)
	/home/runner/work/bsc/bsc/eth/downloader/downloader.go:602 +0x1074
github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).synchronise(0x20?, {0xc0005fdc00, 0x40}, {0x94, 0xc5, 0x90, 0x52, 0xbb, 0x6e, 0x7d, ...}, ...)
	/home/runner/work/bsc/bsc/eth/downloader/downloader.go:442 +0x5b2
github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).LegacySync(0xc001766d00, {0xc0005fdc00, 0x40}, {0x94, 0xc5, 0x90, 0x52, 0xbb, 0x6e, 0x7d, ...}, ...)
	/home/runner/work/bsc/bsc/eth/downloader/downloader.go:331 +0x53
github.com/ethereum/go-ethereum/eth.(*handler).doSync(0xc001a86160, 0x22d2a60a02c56937?)
	/home/runner/work/bsc/bsc/eth/sync.go:236 +0x79
github.com/ethereum/go-ethereum/eth.testChainSyncWithBlobs(0xc0015b6ea0, 0x1, 0x80, 0x49950f?)
	/home/runner/work/bsc/bsc/eth/sync_test.go:173 +0xc6f
github.com/ethereum/go-ethereum/eth.TestSnapSyncWithBlobs(0xc001e67fd0?)
	/home/runner/work/bsc/bsc/eth/sync_test.go:106 +0x25
testing.tRunner(0xc0015b6ea0, 0x1f3c748)
	/opt/hostedtoolcache/go/1.21.11/x64/src/testing/testing.go:1595 +0xff
created by testing.(*T).Run in goroutine 1
	/opt/hostedtoolcache/go/1.21.11/x64/src/testing/testing.go:1648 +0x3ad
FAIL	github.com/ethereum/go-ethereum/eth	3600.093s
ok  	github.com/ethereum/go-ethereum/eth/catalyst	1.049s
````

When submitting logs: please submit them as text and not screenshots.

**Comment by zzzckck** [comment]
Seems it is not fixed yet:
https://github.com/bnb-chain/bsc/actions/runs/9690243822/job/26739746338?pr=2546
```

goroutine 4349 [chan receive, 59 minutes]:
github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).spawnSync(0xc0017b3040, {0xc00195dbc0, 0x5, 0xa?})
	/home/runner/work/bsc/bsc/eth/downloader/downloader.go:623 +0x154
github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).syncWithPeer(0xc0017b3040, 0xc00a233140, {0x94, 0xc5, 0x90, 0x52, 0xbb, 0x6e, 0x7d, 0xfe, ...}, ...)
	/home/runner/work/bsc/bsc/eth/downloader/downloader.go:602 +0x1074
github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).synchronise(0x20?, {0xc000c2ac00, 0x40}, {0x94, 0xc5, 0x90, 0x52, 0xbb, 0x6e, 0x7d, ...}, ...)
	/home/runner/work/bsc/bsc/eth/downloader/downloader.go:442 +0x5b2
github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).LegacySync(0xc0017b3040, {0xc000c2ac00, 0x40}, {0x94, 0xc5, 0x90, 0x52, 0xbb, 0x6e, 0x7d, ...}, ...)
	/home/runner/work/bsc/bsc/eth/downloader/downloader.go:331 +0x53
github.com/ethereum/go-ethereum/eth.(*handler).doSync(0xc0019151e0, 0x22d2a60a02c56937?)
	/home/runner/work/bsc/bsc/eth/sync.go:236 +0x79
github.com/ethereum/go-ethereum/eth.testChainSyncWithBlobs(0xc00160f1e0, 0x1, 0x80, 0x49950f?)
	/home/runner/work/bsc/bsc/eth/sync_test.go:175 +0xc8a
github.com/ethereum/go-ethereum/eth.TestSnapSyncWithBlobs(0xc001d997d0?)
	/home/runner/work/bsc/bsc/eth/sync_test.go:106 +0x25
testing.tRunner(0xc00160f1e0, 0x1f725a8)
	/opt/hostedtoolcache/go/1.21.11/x64/src/testing/testing.go:1595 +0xff
created by testing.(*T).Run in goroutine 1
	/opt/hostedtoolcache/go/1.21.11/x64/src/testing/testing.go:1648 +0x3ad
```

**Comment by zzzckck** [comment]
still has the issue: https://github.com/bnb-chain/bsc/actions/runs/10297380718/job/28500400302?pr=2633

**Comment by zzzckck** [comment]
still has the issue: https://github.com/bnb-chain/bsc/actions/runs/10918883062/job/30305339276?pr=2701
