### ISSUE TITLE
Panic "invalid memory address or nil pointer dereference" when syncing with https://snapshots.48.club/geth.pbss.39422280.tar.zst

### ISSUE THREAD

**Issue by webhype** [bnb-chain/bsc#2532]
#### System information

Geth version: `1.4.10`
OS & Version: Ubuntu 22.04

#### Expected behaviour

That it sync with the snapshot downloaded from https://snapshots.48.club/geth.pbss.39422280.tar.zst and not crash

#### Actual behaviour

`geth_linux` panics with `"invalid memory address or nil pointer dereference"`

#### Steps to reproduce the behaviour

1. Decompress the snapshot downloaded from https://snapshots.48.club/geth.pbss.39422280.tar.zst and put into a folder called mainnet off of the geth root
2. Execute the following `./start.sh`:

```
./geth_linux \
        --config ./config.toml \
        --datadir ./mainnet \
        --cache 32000 \
        --rpc.allow-unprotected-txs \
        --history.transactions 0 \
        --tries-verify-mode none \
        --state.scheme path \
        --db.engine=pebble \
        --http \
        --http.addr=127.0.0.1 \
        --http.api eth,net,web3,txpool,debug,personal \
        --http.corsdomain '' \
        --pprof.addr 0.0.0.0 \
        --pprof \
        --ws \
        --ws.addr=127.0.0.1 \
        --ws.api eth,net,web3,txpool,debug,personal \
        --ws.origins '' \
        --syncmode=full \
        --maxpeers 400 \
        --snapshot=true \
        --history.transactions=90000 \
        --rpc.txfeecap 0 \
        --rpc.allow-unprotected-txs \
        --log.file=/home/gethbnb/gethbnb.log
```

#### Backtrace

````
$ ./start.sh
INFO [06-23|00:55:03.725] Starting pprof server                    addr=http://0.0.0.0:6060/debug/pprof
INFO [06-23|00:55:03.725] Logging configured                       rotate=false format=terminal location=/home/gethbnb/gethbnb.log
INFO [06-23|00:55:03.725] Config environment variable found        envvar=GETH_HTTP_VHOSTS
INFO [06-23|00:55:03.734] Starting Geth on BSC mainnet...
INFO [06-23|00:55:03.736] Maximum peer count                       ETH=400 total=400
INFO [06-23|00:55:03.737] Smartcard socket not found, disabling    err="stat /run/pcscd/pcscd.comm: no such file or directory"
INFO [06-23|00:55:03.737] Using pebble as db engine
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0xd8e48b]

goroutine 7986 [running]:
github.com/ethereum/go-ethereum/core/rawdb.(*ResettableFreezer).AncientRange(0xdfa6e0?, {0x2757760?, 0xc023cc0f48?}, 0xc023cc1048?, 0x23
195c0?, 0xc021a8af90?)
        /home/runner/work/bsc/bsc/core/rawdb/freezer_resettable.go:127 +0x4b
github.com/ethereum/go-ethereum/core/rawdb.ReadStateHistoryMetaList(...)
        /home/runner/work/bsc/bsc/core/rawdb/accessors_state.go:180
github.com/ethereum/go-ethereum/triedb/pathdb.checkHistories(0x0, 0x79c1e9da6612e700?, 0x3b233fe5ced70bfe?, 0xc02c5febe0)
        /home/runner/work/bsc/bsc/triedb/pathdb/history.go:548 +0x7e
github.com/ethereum/go-ethereum/triedb/pathdb.(*Database).Recoverable(0xc0114bdc20, {0xfa, 0x39, 0xe3, 0x55, 0x68, 0x2e, 0x91, 0x4a, 0x0, ...})
        /home/runner/work/bsc/bsc/triedb/pathdb/database.go:420 +0x1cf
github.com/ethereum/go-ethereum/triedb.(*Database).Recoverable(0xc02fabfdc0?, {0xfa, 0x39, 0xe3, 0x55, 0x68, 0x2e, 0x91, 0x4a, 0x0, ...})
        /home/runner/work/bsc/bsc/triedb/database.go:336 +0x3a
github.com/ethereum/go-ethereum/core.(*BlockChain).stateRecoverable(0xc0216ddb80, {0xfa, 0x39, 0xe3, 0x55, 0x68, 0x2e, 0x91, 0x4a, 0x0, ...})
        /home/runner/work/bsc/bsc/core/blockchain_reader.go:374 +0x5f
github.com/ethereum/go-ethereum/core.(*BlockChain).insertSideChain(0xc0216ddb80, 0x27?, 0xc02c5ff960)
        /home/runner/work/bsc/bsc/core/blockchain.go:2512 +0x14d7
github.com/ethereum/go-ethereum/core.(*BlockChain).insertChain(0xc0216ddb80, {0xc027c13640?, 0x2, 0x2}, 0x1)
        /home/runner/work/bsc/bsc/core/blockchain.go:2146 +0xa85
github.com/ethereum/go-ethereum/core.(*BlockChain).InsertChain(0xc0216ddb80, {0xc027c13640?, 0x2, 0x2})
        /home/runner/work/bsc/bsc/core/blockchain.go:2034 +0xb5e
github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).importBlockResults(0xc020dee680, {0xc027c13630, 0x2, 0x768820ee58abde71?})
        /home/runner/work/bsc/bsc/eth/downloader/downloader.go:1405 +0x70e
github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).processFullSyncContent(0xc020dee680, 0xc027d8d080?, 0x0?)
        /home/runner/work/bsc/bsc/eth/downloader/downloader.go:1374 +0xaf
github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).syncWithPeer.func8()
        /home/runner/work/bsc/bsc/eth/downloader/downloader.go:598 +0x1f
github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).spawnSync.func1()
        /home/runner/work/bsc/bsc/eth/downloader/downloader.go:612 +0x66
created by github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).spawnSync in goroutine 7911
        /home/runner/work/bsc/bsc/eth/downloader/downloader.go:612 +0x6e

````

**Comment by webhype** [comment]
The error happens after quite a while, but once it reaches that point, attempts to start again crash immediately. 

Also one would think there's a checksumming process that keeps from decompressing a corrupted file, but I took your suggestion and started downloading a fullnode snapshot from the BSC official snapshot site, https://pub-c0627345c16f47ab858c9469133073a8.r2.dev/geth-pbss-pebble-20240612.tar.lz4

I'll report back if that changed anything...

**Comment by webhype** [comment]
Hi, thanks for your help. As stated, I tried again with this file (which is quite a monster at 2.7 TB) and it worked with 1.4.10.

It also synched fine with https://github.com/48Club/bsc-snapshots?tab=readme-ov-file#geth-fast-node which is explicitly marked as v1.4.10 compatible, in fact it's the only snapshot on that page marked as such. All others are still at 1.4.8, including the one that I had the crash with.

So I will assume for now that the root cause a snapshot that was simply not compatible with 1.4.10, being that the one marked as 1.4.10 on 48.club's page, works.

Thanks again, I will reopen if this crash reappears.
