### ISSUE TITLE
estimate_gas  {'code': -32602, 'message': 'too many arguments, want at most 1'}

### ISSUE THREAD

**Issue by shuyabin** [bnb-chain/bsc#2595]
#### System information

OSX
#### Actual behaviour

Getting gas yesterday has been consistently unsuccessful

#### Steps to reproduce the behaviour

```
w3 = Web3(Web3.HTTPProvider("https://rpc.ankr.com/bsc"))
contract = w3.eth.contract(abi=contractABI)
transactionData = contract.encode_abi("claim", [''])
txParams = {
    "data": transactionData,
    "to": "0xxxxxx",
    "from": "0xxxxx"
}
print(w3.eth.estimate_gas(txParams))
```

#### Backtrace

````
[backtrace]
Traceback (most recent call last):
  File "/Users/xiaoshushu/PycharmProjects/protobuf_test/test_contract/test_contract.py", line 27, in <module>
    print(w3.eth.estimate_gas(txParams))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xiaoshushu/PycharmProjects/protobuf_test/venv/lib/python3.12/site-packages/web3/eth/eth.py", line 316, in estimate_gas
    return self._estimate_gas(transaction, block_identifier, state_override)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xiaoshushu/PycharmProjects/protobuf_test/venv/lib/python3.12/site-packages/web3/module.py", line 75, in caller
    result = w3.manager.request_blocking(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xiaoshushu/PycharmProjects/protobuf_test/venv/lib/python3.12/site-packages/web3/manager.py", line 330, in request_blocking
    return self.formatted_response(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xiaoshushu/PycharmProjects/protobuf_test/venv/lib/python3.12/site-packages/web3/manager.py", line 293, in formatted_response
    raise ValueError(error)
ValueError: {'code': -32602, 'message': 'too many arguments, want at most 1'}
````

![image](https://github.com/user-attachments/assets/c053be74-4fbb-45e0-8ab7-43551e8380ee)

**Comment by zzzckck** [comment]
Could you try other RPC provides?
https://docs.bnbchain.org/bnb-smart-chain/developers/rpc/#bsc-mainnet-chainid-0x38-56-in-decimal
